### ISSUE TITLE
failed to load model 

### ISSUE THREAD

**Issue by ClaudiuStelian** [Randolio/randol_carmeet#1]
[ 1815656] [b2802_GTAProce] MainThrd/ ^1SCRIPT ERROR: @randol_carmeet/cl_carmeet.lua:170: failed to load model '-331467772' - this is likely caused by unreleased assets (waited 2004.0ms)^7

![image](https://github.com/user-attachments/assets/db33e3b1-79f7-49f3-a525-2a88c49f5a99)

**Comment by Randolio** [comment]
Your game build either doesn't stream that particular model or your client is too slow to load the model, Increase the requestModel timeout.

**Comment by ClaudiuStelian** [comment]
Let me try that. It is hard to believe that my client is too slow when my config is Ryzen 7 7800x3d with 3070 8GB
